import React, { ReactNode } from 'react';
import { Logo } from 'types/Logo';
import { ReactComponent as KLogo } from 'assets/images/k.svg';
import { ReactComponent as AngularLogo } from 'assets/images/angular-logo.svg';
import { ReactComponent as AwsLogo } from 'assets/images/aws-logo.svg';
import { ReactComponent as ChromeLogo } from 'assets/images/chrome-logo.svg';
import { ReactComponent as CodesandboxLogo } from 'assets/images/codesandbox-logo.svg';
import { ReactComponent as CssLogo } from 'assets/images/css-logo.svg';
import { ReactComponent as D3Logo } from 'assets/images/d3-logo.svg';
import { ReactComponent as FireFoxLogo } from 'assets/images/firefox-logo.svg';
import { ReactComponent as GithubLogo } from 'assets/images/github-logo.svg';
import { ReactComponent as GoogleCloudLogo } from 'assets/images/google-cloud-logo.svg';
import { ReactComponent as HtmlLogo } from 'assets/images/html-logo.svg';
import { ReactComponent as IllustratorLogo } from 'assets/images/illustrator-logo.svg';
import { ReactComponent as JavascriptLogo } from 'assets/images/javascript-logo.svg';
import { ReactComponent as JestLogo } from 'assets/images/jest-logo.svg';
import { ReactComponent as LinkedIn } from 'assets/images/linkedin-logo.svg';
import { ReactComponent as LodashLogo } from 'assets/images/lodash-logo.svg';
import { ReactComponent as NodejsLogo } from 'assets/images/nodejs-logo.svg';
import { ReactComponent as PhotoshopLogo } from 'assets/images/photoshop-logo.svg';
import { ReactComponent as PostgresLogo } from 'assets/images/postgres-logo.svg';
import { ReactComponent as ReactLogo } from 'assets/images/react-logo.svg';
import { ReactComponent as ReduxLogo } from 'assets/images/redux-logo.svg';
import { ReactComponent as RxjsLogo } from 'assets/images/rxjs-logo.svg';
import { ReactComponent as SafariLogo } from 'assets/images/safari-logo.svg';
import { ReactComponent as SassLogo } from 'assets/images/sass-logo.svg';
import { ReactComponent as FigmaLogo } from 'assets/images/figma-logo.svg';
import { ReactComponent as StorybookLogo } from 'assets/images/storybook-logo.svg';
import { ReactComponent as TypescriptLogo } from 'assets/images/typescript-logo.svg';

export const Logos: any = {
  k: (props: Logo): ReactNode => <KLogo {...props} />,
  angular: (props: Logo): ReactNode => <AngularLogo {...props} />,
  aws: (props: Logo): ReactNode => <AwsLogo {...props} />,
  chrome: (props: Logo): ReactNode => <ChromeLogo {...props} />,
  codesandbox: (props: Logo): ReactNode => <CodesandboxLogo {...props} />,
  css: (props: Logo): ReactNode => <CssLogo {...props} />,
  d3: (props: Logo): ReactNode => <D3Logo {...props} />,
  firefox: (props: Logo): ReactNode => <FireFoxLogo {...props} />,
  github: (props: Logo): ReactNode => <GithubLogo {...props} />,
  googleCloud: (props: Logo): ReactNode => <GoogleCloudLogo {...props} />,
  html: (props: Logo): ReactNode => <HtmlLogo {...props} />,
  illustrator: (props: Logo): ReactNode => <IllustratorLogo {...props} />,
  javascript: (props: Logo): ReactNode => <JavascriptLogo {...props} />,
  jest: (props: Logo): ReactNode => <JestLogo {...props} />,
  linkedin: (props: Logo): ReactNode => <LinkedIn {...props} />,
  lodash: (props: Logo): ReactNode => <LodashLogo {...props} />,
  nodejs: (props: Logo): ReactNode => <NodejsLogo {...props} />,
  photoshop: (props: Logo): ReactNode => <PhotoshopLogo {...props} />,
  postgres: (props: Logo): ReactNode => <PostgresLogo {...props} />,
  react: (props: Logo): ReactNode => <ReactLogo {...props} />,
  redux: (props: Logo): ReactNode => <ReduxLogo {...props} />,
  rxjs: (props: Logo): ReactNode => <RxjsLogo {...props} />,
  safari: (props: Logo): ReactNode => <SafariLogo {...props} />,
  sass: (props: Logo): ReactNode => <SassLogo {...props} />,
  figma: (props: Logo): ReactNode => <FigmaLogo {...props} />,
  storybook: (props: Logo): ReactNode => <StorybookLogo {...props} />,
  typescript: (props: Logo): ReactNode => <TypescriptLogo {...props} />,
};
